server.port=8080
spring.application.name=oracle-dbms-dashboard

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=system
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.sql.init.mode=never