-- =========================================================
-- CLOUD-RESILIENT ORACLE-COMPATIBLE SCHEMA & SEED DATA
-- Used automatically when deploying on free cloud platforms (Render/AWS)
-- without a heavy external Oracle XE instance.
-- =========================================================

CREATE TABLE IF NOT EXISTS CITY (
    CITY VARCHAR(50) PRIMARY KEY,
    STATE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SUPPLIER (
    SUPPLIERID VARCHAR(10) PRIMARY KEY,
    SNAME VARCHAR(100),
    CITY VARCHAR(50),
    FOREIGN KEY (CITY) REFERENCES CITY(CITY)
);

CREATE TABLE IF NOT EXISTS SUPPLIER_PHONE (
    SUPPLIERID VARCHAR(10) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (SUPPLIERID, PHONE),
    FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCTID VARCHAR(10) PRIMARY KEY,
    PNAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    UNITPRICE DECIMAL(10,2) CHECK (UNITPRICE >= 0)
);

CREATE TABLE IF NOT EXISTS PERISHABLE_PRODUCT (
    PRODUCTID VARCHAR(10) PRIMARY KEY,
    SHELFLIFEDAYS INT CHECK (SHELFLIFEDAYS > 0),
    STORAGETEMPC VARCHAR(50),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HAZARDOUS_PRODUCT (
    PRODUCTID VARCHAR(10) PRIMARY KEY,
    HAZARDCLASS VARCHAR(100),
    HANDLINGNOTE VARCHAR(200),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLIES (
    SUPPLIERID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    LEADTIMEDAYS INT,
    PRIMARY KEY (SUPPLIERID, PRODUCTID),
    FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE IF NOT EXISTS INSPECTION (
    INSPID VARCHAR(10) PRIMARY KEY,
    SUPPLIERID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    INSPDATE DATE NOT NULL,
    RESULT VARCHAR(50),
    FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE IF NOT EXISTS WAREHOUSE (
    WAREHOUSEID VARCHAR(10) PRIMARY KEY,
    WNAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50),
    CAPACITY INT,
    MANAGERID VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMPID VARCHAR(10) PRIMARY KEY,
    ENAME VARCHAR(100),
    ROLE VARCHAR(50),
    SALARY DECIMAL(12,2) CHECK (SALARY >= 0),
    WAREHOUSEID VARCHAR(10),
    SUPERVISORID VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS MANAGER (
    EMPID VARCHAR(10) PRIMARY KEY,
    LEVELNO VARCHAR(50),
    BONUS DECIMAL(10,2),
    FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER (
    EMPID VARCHAR(10) PRIMARY KEY,
    LICENSENO VARCHAR(50),
    EXPIRY DATE,
    FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER_CITY (
    DRIVERID VARCHAR(10) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (DRIVERID, CITY),
    FOREIGN KEY (DRIVERID) REFERENCES DRIVER(EMPID),
    FOREIGN KEY (CITY) REFERENCES CITY(CITY)
);

CREATE TABLE IF NOT EXISTS STOCK (
    WAREHOUSEID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    QUANTITY INT CHECK (QUANTITY >= 0),
    PRIMARY KEY (WAREHOUSEID, PRODUCTID),
    FOREIGN KEY (WAREHOUSEID) REFERENCES WAREHOUSE(WAREHOUSEID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTID VARCHAR(10) PRIMARY KEY,
    CNAME VARCHAR(100) NOT NULL,
    STREET VARCHAR(100),
    CITY VARCHAR(50),
    PHONE VARCHAR(20),
    FOREIGN KEY (CITY) REFERENCES CITY(CITY)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDERID VARCHAR(10) PRIMARY KEY,
    ORDERDATE DATE NOT NULL,
    STATUS VARCHAR(30),
    CUSTID VARCHAR(10) NOT NULL,
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDERID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    QTY INT CHECK (QTY > 0),
    PRICE DECIMAL(10,2) CHECK (PRICE >= 0),
    PRIMARY KEY (ORDERID, PRODUCTID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE IF NOT EXISTS ORDER_DRIVER (
    ORDERID VARCHAR(10) NOT NULL,
    DRIVERID VARCHAR(10) NOT NULL,
    PRIMARY KEY (ORDERID, DRIVERID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
    FOREIGN KEY (DRIVERID) REFERENCES DRIVER(EMPID)
);

CREATE TABLE IF NOT EXISTS DELIVERY_DUTY (
    ORDERID VARCHAR(10) NOT NULL,
    DRIVERID VARCHAR(10) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (ORDERID, CITY),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
    FOREIGN KEY (DRIVERID) REFERENCES DRIVER(EMPID),
    FOREIGN KEY (CITY) REFERENCES CITY(CITY)
);

CREATE TABLE IF NOT EXISTS GOODS_MOVEMENT (
    MOVEMENTID VARCHAR(10) PRIMARY KEY,
    ORDERID VARCHAR(10) NOT NULL,
    WAREHOUSEID VARCHAR(10) NOT NULL,
    MOVEDATE DATE,
    STATUS VARCHAR(30),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
    FOREIGN KEY (WAREHOUSEID) REFERENCES WAREHOUSE(WAREHOUSEID)
);

CREATE TABLE IF NOT EXISTS SHIPMENT (
    MOVEMENTID VARCHAR(10) PRIMARY KEY,
    DELIVERYDATE DATE,
    FOREIGN KEY (MOVEMENTID) REFERENCES GOODS_MOVEMENT(MOVEMENTID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GOODS_RETURN (
    MOVEMENTID VARCHAR(10) PRIMARY KEY,
    REASON VARCHAR(200),
    REFUNDAMT DECIMAL(10,2),
    FOREIGN KEY (MOVEMENTID) REFERENCES GOODS_MOVEMENT(MOVEMENTID) ON DELETE CASCADE
);

-- SEED DATA
MERGE INTO CITY KEY(CITY) VALUES ('Chennai', 'Tamil Nadu'), ('Mumbai', 'Maharashtra');

MERGE INTO SUPPLIER KEY(SUPPLIERID) VALUES 
('S01', 'Apex Agro Supplies', 'Chennai'),
('S03', 'Metro Wholesale Mills', 'Mumbai'),
('S05', 'Delta Cold & Chemicals', 'Chennai');

MERGE INTO SUPPLIER_PHONE KEY(SUPPLIERID, PHONE) VALUES 
('S01', '9845012345'),
('S01', '08022334455'),
('S03', '9820011122'),
('S05', '9840199887'),
('S05', '04424851212');

MERGE INTO PRODUCT KEY(PRODUCTID) VALUES 
('P-100', 'Basmati Rice', 'Staples', 480.00),
('P-104', 'Sunflower Oil', 'Oils', 132.00),
('P-108', 'Sona Masoori', 'Staples', 445.00),
('P-210', 'Frozen Peas', 'Frozen', 96.00);

MERGE INTO PERISHABLE_PRODUCT KEY(PRODUCTID) VALUES 
('P-210', 90, '-18°C');

MERGE INTO CUSTOMER KEY(CUSTID) VALUES 
('C-01', 'Shama Retail', '12 MG Rd', 'Chennai', '9840011223'),
('C-03', 'Metro Mart', '5 Link Rd', 'Mumbai', '9820044556'),
('C-05', 'Anand Stores', '7 Anna Salai', 'Chennai', '9845567788');

MERGE INTO ORDERS KEY(ORDERID) VALUES 
('O-101', DATE '2026-04-02', 'SHIPPED', 'C-01'),
('O-102', DATE '2026-04-05', 'NEW', 'C-03'),
('O-103', DATE '2026-04-09', 'SHIPPED', 'C-01'),
('O-104', DATE '2026-04-11', 'NEW', 'C-05'),
('O-105', DATE '2026-04-14', 'SHIPPED', 'C-03'),
('O-106', DATE '2026-04-16', 'NEW', 'C-05');

MERGE INTO ORDER_ITEM KEY(ORDERID, PRODUCTID) VALUES 
('O-101', 'P-100', 20, 480.00),
('O-101', 'P-104', 50, 132.00),
('O-102', 'P-210', 30, 96.00),
('O-103', 'P-100', 15, 480.00),
('O-104', 'P-108', 12, 445.00),
('O-105', 'P-104', 25, 132.00),
('O-105', 'P-210', 40, 96.00),
('O-106', 'P-100', 18, 480.00);

MERGE INTO EMPLOYEE KEY(EMPID) VALUES 
('D-05', 'Ramesh Kumar', 'Driver', 32000, NULL, NULL),
('D-09', 'Suresh Patil', 'Driver', 34000, NULL, NULL),
('D-11', 'Venkatesh Rao', 'Driver', 31000, NULL, NULL),
('M-01', 'Kavita Sharma', 'Manager', 85000, NULL, NULL);

MERGE INTO DRIVER KEY(EMPID) VALUES 
('D-05', 'TN-02-2021-998', DATE '2028-12-31'),
('D-09', 'MH-01-2020-412', DATE '2027-08-15'),
('D-11', 'TN-05-2022-771', DATE '2029-05-20');

MERGE INTO MANAGER KEY(EMPID) VALUES 
('M-01', 'L3', 15000.00);

MERGE INTO ORDER_DRIVER KEY(ORDERID, DRIVERID) VALUES 
('O-101', 'D-05'),
('O-102', 'D-09'),
('O-103', 'D-05'),
('O-104', 'D-05'),
('O-105', 'D-09'),
('O-106', 'D-11');

MERGE INTO DELIVERY_DUTY KEY(ORDERID, CITY) VALUES 
('O-101', 'D-05', 'Chennai'),
('O-101', 'D-09', 'Mumbai'),
('O-102', 'D-09', 'Mumbai'),
('O-103', 'D-05', 'Chennai'),
('O-104', 'D-05', 'Chennai'),
('O-105', 'D-09', 'Mumbai'),
('O-106', 'D-11', 'Chennai');
