-- =========================================================
-- FINAL DBMS LAB SCHEMA
-- Based on the handwritten ER model / normalization sheets
-- =========================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE GOODS_RETURN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHIPMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GOODS_MOVEMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DELIVERY_DUTY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_DRIVER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DRIVER_CITY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DRIVER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MANAGER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STOCK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WAREHOUSE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INSPECTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HAZARDOUS_PRODUCT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERISHABLE_PRODUCT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER_PHONE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =========================================================
-- CITY
-- =========================================================

CREATE TABLE CITY (
    CITY VARCHAR2(50) PRIMARY KEY,
    STATE VARCHAR2(50) NOT NULL
);

-- =========================================================
-- SUPPLIER
-- =========================================================

CREATE TABLE SUPPLIER (
    SUPPLIERID VARCHAR2(10) PRIMARY KEY,
    SNAME VARCHAR2(100),
    CITY VARCHAR2(50),
    CONSTRAINT FK_SUPPLIER_CITY
        FOREIGN KEY (CITY) REFERENCES CITY(CITY)
);

-- =========================================================
-- SUPPLIER_PHONE
-- =========================================================

CREATE TABLE SUPPLIER_PHONE (
    SUPPLIERID VARCHAR2(10) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_SUPPLIER_PHONE
        PRIMARY KEY (SUPPLIERID, PHONE),
    CONSTRAINT FK_SUPPLIER_PHONE
        FOREIGN KEY (SUPPLIERID)
        REFERENCES SUPPLIER(SUPPLIERID)
);

-- =========================================================
-- PRODUCT
-- =========================================================

CREATE TABLE PRODUCT (
    PRODUCTID VARCHAR2(10) PRIMARY KEY,
    PNAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    UNITPRICE NUMBER(10,2) CHECK (UNITPRICE >= 0)
);

-- =========================================================
-- PERISHABLE_PRODUCT
-- =========================================================

CREATE TABLE PERISHABLE_PRODUCT (
    PRODUCTID VARCHAR2(10) PRIMARY KEY,
    SHELFLIFEDAYS NUMBER(5) CHECK (SHELFLIFEDAYS > 0),
    STORAGETEMPC VARCHAR2(50),
    CONSTRAINT FK_PERISHABLE_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
        ON DELETE CASCADE
);

-- =========================================================
-- HAZARDOUS_PRODUCT
-- =========================================================

CREATE TABLE HAZARDOUS_PRODUCT (
    PRODUCTID VARCHAR2(10) PRIMARY KEY,
    HAZARDCLASS VARCHAR2(100),
    HANDLINGNOTE VARCHAR2(200),
    CONSTRAINT FK_HAZARDOUS_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
        ON DELETE CASCADE
);

-- =========================================================
-- SUPPLIES
-- =========================================================

CREATE TABLE SUPPLIES (
    SUPPLIERID VARCHAR2(10) NOT NULL,
    PRODUCTID VARCHAR2(10) NOT NULL,
    LEADTIMEDAYS NUMBER(5),
    CONSTRAINT PK_SUPPLIES
        PRIMARY KEY (SUPPLIERID, PRODUCTID),
    CONSTRAINT FK_SUPPLIES_SUPPLIER
        FOREIGN KEY (SUPPLIERID)
        REFERENCES SUPPLIER(SUPPLIERID),
    CONSTRAINT FK_SUPPLIES_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
);

-- =========================================================
-- INSPECTION
-- =========================================================

CREATE TABLE INSPECTION (
    INSPID VARCHAR2(10) PRIMARY KEY,
    SUPPLIERID VARCHAR2(10) NOT NULL,
    PRODUCTID VARCHAR2(10) NOT NULL,
    INSPDATE DATE NOT NULL,
    RESULT VARCHAR2(50),
    CONSTRAINT FK_INSPECTION_SUPPLIER
        FOREIGN KEY (SUPPLIERID)
        REFERENCES SUPPLIER(SUPPLIERID),
    CONSTRAINT FK_INSPECTION_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
);

-- =========================================================
-- WAREHOUSE
-- =========================================================

CREATE TABLE WAREHOUSE (
    WAREHOUSEID VARCHAR2(10) PRIMARY KEY,
    WNAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(50),
    CAPACITY NUMBER(10),
    MANAGERID VARCHAR2(10)
);

-- =========================================================
-- EMPLOYEE
-- =========================================================

CREATE TABLE EMPLOYEE (
    EMPID VARCHAR2(10) PRIMARY KEY,
    ENAME VARCHAR2(100) ,
    ROLE VARCHAR2(50),
    SALARY NUMBER(12,2) CHECK (SALARY >= 0),
    WAREHOUSEID VARCHAR2(10),
    SUPERVISORID VARCHAR2(10)
);

-- =========================================================
-- MANAGER
-- =========================================================

CREATE TABLE MANAGER (
    EMPID VARCHAR2(10) PRIMARY KEY,
    LEVELNO VARCHAR2(50),
    BONUS NUMBER(10,2),
    CONSTRAINT FK_MANAGER_EMPLOYEE
        FOREIGN KEY (EMPID)
        REFERENCES EMPLOYEE(EMPID)
        ON DELETE CASCADE
);

-- =========================================================
-- DRIVER
-- =========================================================

CREATE TABLE DRIVER (
    EMPID VARCHAR2(10) PRIMARY KEY,
    LICENSENO VARCHAR2(50),
    EXPIRY DATE,
    CONSTRAINT FK_DRIVER_EMPLOYEE
        FOREIGN KEY (EMPID)
        REFERENCES EMPLOYEE(EMPID)
        ON DELETE CASCADE
);

-- =========================================================
-- DRIVER_CITY
-- =========================================================

CREATE TABLE DRIVER_CITY (
    DRIVERID VARCHAR2(10) NOT NULL,
    CITY VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_DRIVER_CITY
        PRIMARY KEY (DRIVERID, CITY),
    CONSTRAINT FK_DRIVER_CITY_DRIVER
        FOREIGN KEY (DRIVERID)
        REFERENCES DRIVER(EMPID),
    CONSTRAINT FK_DRIVER_CITY_CITY
        FOREIGN KEY (CITY)
        REFERENCES CITY(CITY)
);

-- =========================================================
-- STOCK
-- =========================================================

CREATE TABLE STOCK (
    WAREHOUSEID VARCHAR2(10) NOT NULL,
    PRODUCTID VARCHAR2(10) NOT NULL,
    QUANTITY NUMBER(10) CHECK (QUANTITY >= 0),
    CONSTRAINT PK_STOCK
        PRIMARY KEY (WAREHOUSEID, PRODUCTID),
    CONSTRAINT FK_STOCK_WAREHOUSE
        FOREIGN KEY (WAREHOUSEID)
        REFERENCES WAREHOUSE(WAREHOUSEID),
    CONSTRAINT FK_STOCK_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
);

-- =========================================================
-- CUSTOMER
-- =========================================================

CREATE TABLE CUSTOMER (
    CUSTID VARCHAR2(10) PRIMARY KEY,
    CNAME VARCHAR2(100) NOT NULL,
    STREET VARCHAR2(100),
    CITY VARCHAR2(50),
    PHONE VARCHAR2(20),
    CONSTRAINT FK_CUSTOMER_CITY
        FOREIGN KEY (CITY)
        REFERENCES CITY(CITY)
);

-- =========================================================
-- ORDERS
-- =========================================================

CREATE TABLE ORDERS (
    ORDERID VARCHAR2(10) PRIMARY KEY,
    ORDERDATE DATE NOT NULL,
    STATUS VARCHAR2(30),
    CUSTID VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTID)
        REFERENCES CUSTOMER(CUSTID)
);

-- =========================================================
-- ORDER_ITEM
-- =========================================================

CREATE TABLE ORDER_ITEM (
    ORDERID VARCHAR2(10) NOT NULL,
    PRODUCTID VARCHAR2(10) NOT NULL,
    QTY NUMBER(10) CHECK (QTY > 0),
    PRICE NUMBER(10,2) CHECK (PRICE >= 0),
    CONSTRAINT PK_ORDER_ITEM
        PRIMARY KEY (ORDERID, PRODUCTID),
    CONSTRAINT FK_ORDER_ITEM_ORDER
        FOREIGN KEY (ORDERID)
        REFERENCES ORDERS(ORDERID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT
        FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT(PRODUCTID)
);

-- =========================================================
-- ORDER_DRIVER
-- =========================================================

CREATE TABLE ORDER_DRIVER (
    ORDERID VARCHAR2(10) NOT NULL,
    DRIVERID VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_ORDER_DRIVER
        PRIMARY KEY (ORDERID, DRIVERID),
    CONSTRAINT FK_ORDER_DRIVER_ORDER
        FOREIGN KEY (ORDERID)
        REFERENCES ORDERS(ORDERID),
    CONSTRAINT FK_ORDER_DRIVER_DRIVER
        FOREIGN KEY (DRIVERID)
        REFERENCES DRIVER(EMPID)
);

-- =========================================================
-- DELIVERY_DUTY
-- =========================================================

CREATE TABLE DELIVERY_DUTY (
    ORDERID VARCHAR2(10) NOT NULL,
    DRIVERID VARCHAR2(10) NOT NULL,
    CITY VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_DELIVERY_DUTY
        PRIMARY KEY (ORDERID, CITY),
    CONSTRAINT FK_DELIVERY_ORDER
        FOREIGN KEY (ORDERID)
        REFERENCES ORDERS(ORDERID),
    CONSTRAINT FK_DELIVERY_DRIVER
        FOREIGN KEY (DRIVERID)
        REFERENCES DRIVER(EMPID),
    CONSTRAINT FK_DELIVERY_CITY
        FOREIGN KEY (CITY)
        REFERENCES CITY(CITY)
);

-- =========================================================
-- GOODS_MOVEMENT
-- =========================================================

CREATE TABLE GOODS_MOVEMENT (
    MOVEMENTID VARCHAR2(10) PRIMARY KEY,
    ORDERID VARCHAR2(10) NOT NULL,
    WAREHOUSEID VARCHAR2(10) NOT NULL,
    MOVEDATE DATE,
    STATUS VARCHAR2(30),
    CONSTRAINT FK_MOVEMENT_ORDER
        FOREIGN KEY (ORDERID)
        REFERENCES ORDERS(ORDERID),
    CONSTRAINT FK_MOVEMENT_WAREHOUSE
        FOREIGN KEY (WAREHOUSEID)
        REFERENCES WAREHOUSE(WAREHOUSEID)
);

-- =========================================================
-- SHIPMENT
-- =========================================================

CREATE TABLE SHIPMENT (
    MOVEMENTID VARCHAR2(10) PRIMARY KEY,
    DELIVERYDATE DATE,
    CONSTRAINT FK_SHIPMENT_MOVEMENT
        FOREIGN KEY (MOVEMENTID)
        REFERENCES GOODS_MOVEMENT(MOVEMENTID)
        ON DELETE CASCADE
);

-- =========================================================
-- GOODS_RETURN
-- =========================================================

CREATE TABLE GOODS_RETURN (
    MOVEMENTID VARCHAR2(10) PRIMARY KEY,
    REASON VARCHAR2(200),
    REFUNDAMT NUMBER(10,2),
    CONSTRAINT FK_RETURN_MOVEMENT
        FOREIGN KEY (MOVEMENTID)
        REFERENCES GOODS_MOVEMENT(MOVEMENTID)
        ON DELETE CASCADE
);
-- =========================================================
-- ADDITIONAL FOREIGN KEY RELATIONSHIPS
-- =========================================================

-- Warehouse belongs to a City
ALTER TABLE WAREHOUSE
ADD CONSTRAINT FK_WAREHOUSE_CITY
FOREIGN KEY (CITY)
REFERENCES CITY(CITY);

-- Warehouse is managed by a Manager
ALTER TABLE WAREHOUSE
ADD CONSTRAINT FK_WAREHOUSE_MANAGER
FOREIGN KEY (MANAGERID)
REFERENCES MANAGER(EMPID);

-- Employee works in a Warehouse
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_WAREHOUSE
FOREIGN KEY (WAREHOUSEID)
REFERENCES WAREHOUSE(WAREHOUSEID);

-- Employee can report to another Employee
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_SUPERVISOR
FOREIGN KEY (SUPERVISORID)
REFERENCES EMPLOYEE(EMPID);

COMMIT;
