-- Selected queries corresponding to the supplied DBMS Lab Assessment 2.

-- Subqueries / nested queries
SELECT SID,SNAME FROM STUDENT
WHERE SID IN(SELECT SID FROM APPLY WHERE STREAM='CSE');

SELECT DISTINCT CNAME FROM APPLY
WHERE SID IN(SELECT SID FROM STUDENT WHERE SNAME LIKE 'S%');

SELECT SID,SNAME FROM STUDENT
WHERE SID NOT IN(SELECT SID FROM APPLY WHERE CNAME='DAV');

SELECT * FROM EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

-- INNER JOIN
SELECT e.EMPLOYEE_ID,e.EMPLOYEE_NAME,e.SALARY,d.DEPARTMENT_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID=d.DEPARTMENT_ID;

-- LEFT OUTER JOIN
SELECT c.CUSTOMER_ID,c.CUSTOMER_NAME,o.ORDER_ID,o.ORDER_DATE
FROM CUSTOMERS c LEFT JOIN ORDERS o
ON c.CUSTOMER_ID=o.CUSTOMER_ID;

-- LEFT JOIN products/suppliers
SELECT p.PRODUCT_ID,p.PRODUCT_NAME,s.SUPPLIER_NAME
FROM PRODUCTS p LEFT JOIN SUPPLIERS s
ON p.SUPPLIER_ID=s.SUPPLIER_ID;

-- FULL OUTER JOIN
SELECT s.STUDENT_ID,s.STUDENT_NAME,c.COURSE_ID,c.COURSE_NAME
FROM STUDENTS s
FULL OUTER JOIN ENROLLMENTS e ON e.STUDENT_ID=s.STUDENT_ID
FULL OUTER JOIN COURSES c ON c.COURSE_ID=e.COURSE_ID;

-- CROSS JOIN
SELECT p.PRODUCT_ID,p.PRODUCT_NAME,c.CATEGORY_ID,c.CATEGORY_NAME
FROM PRODUCTS p CROSS JOIN CATEGORIES c;

-- SELF JOIN: employees with same manager
SELECT e1.EMPLOYEE_ID AS EMP1,e2.EMPLOYEE_ID AS EMP2,e1.MANAGER_ID
FROM EMPLOYEES e1 JOIN EMPLOYEES e2
ON e1.MANAGER_ID=e2.MANAGER_ID
AND e1.EMPLOYEE_ID<e2.EMPLOYEE_ID;

-- Order details + shipments
SELECT od.ORDER_ID,od.PRODUCT_ID,od.QUANTITY,sh.SHIPMENT_ID,sh.SHIPMENT_DATE
FROM ORDER_DETAILS od JOIN SHIPMENTS sh
ON sh.ORDER_ID=od.ORDER_ID AND sh.PRODUCT_ID=od.PRODUCT_ID;

-- Salary > 80000 with department
SELECT e.EMPLOYEE_ID,e.EMPLOYEE_NAME,e.SALARY,d.DEPARTMENT_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d
ON e.DEPARTMENT_ID=d.DEPARTMENT_ID
WHERE e.SALARY>80000;

-- Projects including projects without employees
SELECT p.PROJECT_ID,p.PROJECT_NAME,e.EMPLOYEE_ID,e.EMPLOYEE_NAME
FROM PROJECTS p LEFT JOIN EMPLOYEES e
ON e.PROJECT_ID=p.PROJECT_ID;

-- Cartesian product departments x locations
SELECT d.DEPARTMENT_ID,d.DEPARTMENT_NAME,l.LOCATION_ID,l.LOCATION_NAME
FROM DEPARTMENTS d CROSS JOIN LOCATIONS l;

-- Example CRUD
UPDATE EMPLOYEES SET SALARY=SALARY*1.50 WHERE EMPLOYEE_ID=101;
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID=104;
